// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace rocket_api.Models
{
    public class Users
    {
        [Key]
        [Column("usersId")]
        public int UsersId { get; set; }

        [Required]
        [Column("name")]
        [StringLength(64)]
        public string Name { get; set; }

        [Column("birthday", TypeName = "date")]
        public DateTime Birthday { get; set; }

        [Required]
        [Column("email")]
        [StringLength(100)]
        public string Email { get; set; }

        [Required]
        [Column("phone")]
        [StringLength(15)]
        public string Phone { get; set; }

        [Column("createAt", TypeName = "date")]
        public DateTime CreateAt { get; set; }
    }
}